[project]
name = "ex-7-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "line-profiler>=4.2.0",
    "memory-profiler>=0.61.0",
]
