[project]
name = "abstraction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "pyyaml>=6.0.2",
    "typer>=0.15.3",
]
